# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2017.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion-2017.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fisk/CLionProjects/sfml-sandbox

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fisk/CLionProjects/sfml-sandbox

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2017.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2017.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/clion-2017.1.3/bin/cmake/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fisk/CLionProjects/sfml-sandbox/CMakeFiles /home/fisk/CLionProjects/sfml-sandbox/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fisk/CLionProjects/sfml-sandbox/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sfml_sandbox_test

# Build rule for target.
sfml_sandbox_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfml_sandbox_test
.PHONY : sfml_sandbox_test

# fast build rule for target.
sfml_sandbox_test/fast:
	$(MAKE) -f CMakeFiles/sfml_sandbox_test.dir/build.make CMakeFiles/sfml_sandbox_test.dir/build
.PHONY : sfml_sandbox_test/fast

#=============================================================================
# Target rules for targets named sfml_sandbox

# Build rule for target.
sfml_sandbox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfml_sandbox
.PHONY : sfml_sandbox

# fast build rule for target.
sfml_sandbox/fast:
	$(MAKE) -f CMakeFiles/sfml_sandbox.dir/build.make CMakeFiles/sfml_sandbox.dir/build
.PHONY : sfml_sandbox/fast

src/GameBoard.o: src/GameBoard.cpp.o

.PHONY : src/GameBoard.o

# target to build an object file
src/GameBoard.cpp.o:
	$(MAKE) -f CMakeFiles/sfml_sandbox.dir/build.make CMakeFiles/sfml_sandbox.dir/src/GameBoard.cpp.o
.PHONY : src/GameBoard.cpp.o

src/GameBoard.i: src/GameBoard.cpp.i

.PHONY : src/GameBoard.i

# target to preprocess a source file
src/GameBoard.cpp.i:
	$(MAKE) -f CMakeFiles/sfml_sandbox.dir/build.make CMakeFiles/sfml_sandbox.dir/src/GameBoard.cpp.i
.PHONY : src/GameBoard.cpp.i

src/GameBoard.s: src/GameBoard.cpp.s

.PHONY : src/GameBoard.s

# target to generate assembly for a file
src/GameBoard.cpp.s:
	$(MAKE) -f CMakeFiles/sfml_sandbox.dir/build.make CMakeFiles/sfml_sandbox.dir/src/GameBoard.cpp.s
.PHONY : src/GameBoard.cpp.s

src/GamePiece.o: src/GamePiece.cpp.o

.PHONY : src/GamePiece.o

# target to build an object file
src/GamePiece.cpp.o:
	$(MAKE) -f CMakeFiles/sfml_sandbox.dir/build.make CMakeFiles/sfml_sandbox.dir/src/GamePiece.cpp.o
.PHONY : src/GamePiece.cpp.o

src/GamePiece.i: src/GamePiece.cpp.i

.PHONY : src/GamePiece.i

# target to preprocess a source file
src/GamePiece.cpp.i:
	$(MAKE) -f CMakeFiles/sfml_sandbox.dir/build.make CMakeFiles/sfml_sandbox.dir/src/GamePiece.cpp.i
.PHONY : src/GamePiece.cpp.i

src/GamePiece.s: src/GamePiece.cpp.s

.PHONY : src/GamePiece.s

# target to generate assembly for a file
src/GamePiece.cpp.s:
	$(MAKE) -f CMakeFiles/sfml_sandbox.dir/build.make CMakeFiles/sfml_sandbox.dir/src/GamePiece.cpp.s
.PHONY : src/GamePiece.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/sfml_sandbox.dir/build.make CMakeFiles/sfml_sandbox.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/sfml_sandbox.dir/build.make CMakeFiles/sfml_sandbox.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/sfml_sandbox.dir/build.make CMakeFiles/sfml_sandbox.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/sfml_sandbox_tests.o: test/sfml_sandbox_tests.cpp.o

.PHONY : test/sfml_sandbox_tests.o

# target to build an object file
test/sfml_sandbox_tests.cpp.o:
	$(MAKE) -f CMakeFiles/sfml_sandbox_test.dir/build.make CMakeFiles/sfml_sandbox_test.dir/test/sfml_sandbox_tests.cpp.o
.PHONY : test/sfml_sandbox_tests.cpp.o

test/sfml_sandbox_tests.i: test/sfml_sandbox_tests.cpp.i

.PHONY : test/sfml_sandbox_tests.i

# target to preprocess a source file
test/sfml_sandbox_tests.cpp.i:
	$(MAKE) -f CMakeFiles/sfml_sandbox_test.dir/build.make CMakeFiles/sfml_sandbox_test.dir/test/sfml_sandbox_tests.cpp.i
.PHONY : test/sfml_sandbox_tests.cpp.i

test/sfml_sandbox_tests.s: test/sfml_sandbox_tests.cpp.s

.PHONY : test/sfml_sandbox_tests.s

# target to generate assembly for a file
test/sfml_sandbox_tests.cpp.s:
	$(MAKE) -f CMakeFiles/sfml_sandbox_test.dir/build.make CMakeFiles/sfml_sandbox_test.dir/test/sfml_sandbox_tests.cpp.s
.PHONY : test/sfml_sandbox_tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... sfml_sandbox_test"
	@echo "... sfml_sandbox"
	@echo "... src/GameBoard.o"
	@echo "... src/GameBoard.i"
	@echo "... src/GameBoard.s"
	@echo "... src/GamePiece.o"
	@echo "... src/GamePiece.i"
	@echo "... src/GamePiece.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/sfml_sandbox_tests.o"
	@echo "... test/sfml_sandbox_tests.i"
	@echo "... test/sfml_sandbox_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

